useDotenv: true

org: monichre
service: is-elon-being-an-asshole
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    OPENAI_API_KEY: ${OPENAI_API_KEY}
    OPENAI_API_URL: ${OPENAI_API_URL}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    TWITTER_API_BEARER_TOKEN: ${env:TWITTER_API_BEARER_TOKEN}
    TWITTER_API_KEY: ${env:TWITTER_API_KEY}
    TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}



functions:
  isElonBeingAnAsshole:
    handler: handler.isElonBeingAnAsshole
    events:
      # - schedule: rate(15 minute)
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

