useDotenv: true

org: monichre
app: is-elon-being-an-asshole
service: is-elon-being-an-asshole
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    OPENAI_API_KEY: ${OPENAI_API_KEY}
    OPENAI_API_URL: ${OPENAI_API_URL}
    TWITTER_API_ACCESS_TOKEN: ${env:TWITTER_API_ACCESS_TOKEN}
    TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
    TWITTER_API_BEARER_TOKEN: ${env:TWITTER_API_BEARER_TOKEN}
    


functions:
  isElonBeingAnAsshole:
    handler: handler.isElonBeingAnAsshole
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

